backend:
  name: github
  repo: OlehKotynskyi/test-cms # Заміни на свій GitHub репозиторій
  branch: main # Гілка, з якою працюватиме CMS

media_folder: "img" # Папка для завантаження медіафайлів
public_folder: "/img" # Шлях для доступу до медіафайлів на сайті

collections:
  - name: "pages"
    label: "Сторінки"
    files:
      - file: "index.md"
        label: "Головна сторінка"
        name: "index"
        fields:
          - { label: "Заголовок", name: "title", widget: "string" }
          - { label: "Текст", name: "body", widget: "markdown" }
