backend:
  name: git-gateway
  repo: OlehKotynskyi/test-cms
  branch: main

media_folder: "img"
public_folder: "/img"

collections:
  - name: "pages"
    label: "Сторінки"
    files:
      - file: "home.md" # Змінили з index.md на home.md
        label: "Головна сторінка"
        name: "home"
        fields:
          - { label: "Заголовок", name: "title", widget: "string" }
          - { label: "Текст", name: "body", widget: "markdown" }
